## get catalog and create summary file
GWASCatalogFileDownloadURL: "https://www.ebi.ac.uk/gwas/api/search/downloads/studies/v1.0.2.1"

DownloadHeader:
    Cookie: 'xxxx'
    Host: 'www.ebi.ac.uk'
    Referer: 'https://www.ebi.ac.uk/gwas/docs/file-downloads'
    User-Agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36'

CatalogFilePath: "/xx/xx"
SummaryFilePath: "/xx/xx"
LastUpdatedTime: "xxxx-xx-xx"

## create harmonised file and get file urls
HarmonisedFilePath: "xx/harmonised.csv"
ConcurrentNum: 8

## download info
BaseDir: 'xxx/data'
CommandFile: "xxx/commands.txt"
AsperaSSH: "xxx/asperaweb_id_dsa.openssh"
ProcessNum: 10
